version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./database:/app/database
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - PORT=8080
      - TZ=Asia/Makassar
    restart: unless-stopped
